Feature/fw
WattRex/Regenerative-Battery-Cycler pull request #43
Opened 2023-06-02 07:43 UTC by RobertoAldea

Change project configuration, test and hal sys

2023-06-02 11:23 UTC, pastorpflores requested changes

2023-06-02 11:23 UTC, pastorpflores commented on firmware/Sources/Test/test.c
> +<<<<<<< Updated upstream
wtf. A merge is not well resolver here?

2023-06-02 11:23 UTC, pastorpflores commented on firmware/project_config/EPC_CONF/epc_conf.h
> +<<<<<<< Updated upstream
another issue with a merge here??

2023-06-02 11:50 UTC, RobertoAldea commented on firmware/Sources/Test/test.c
> +<<<<<<< Updated upstream
Solved in last commit

2023-06-02 11:50 UTC, RobertoAldea commented on firmware/project_config/EPC_CONF/epc_conf.h
> +<<<<<<< Updated upstream
Solved in last commit

2023-06-05 07:47 UTC, pastorpflores approved these changes

2023-06-05 07:48 UTC, pastorpflores commented
@mariuscrsn please resolve conflicts :)

2023-06-05 08:43 UTC, merged